--BB_ADDR 테이블

SELECT * FROM BB_ADDR;

DROP TABLE BB_ADDR
CASCADE CONSTRAINT;

DROP SEQUENCE BB_ADDR_SEQ;

CREATE TABLE BB_ADDR(
	SEQ NUMBER(10) PRIMARY KEY,
	MEMBER_SEQ NUMBER(10) NOT NULL,
	ADDRESS VARCHAR2(200) NOT NULL,
	LAT VARCHAR2(100) NOT NULL,
	LNG VARCHAR2(100) NOT NULL,
	MEMO VARCHAR2(200),
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_ADDR_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE BB_ADDR
ADD CONSTRAINT FK_BB_M_ADDR_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);
