--BB_BURGER

SELECT * FROM BB_BURGER;

DROP TABLE BB_BURGER
CASCADE CONSTRAINT;

DROP SEQUENCE BB_BURGER_SEQ;

CREATE TABLE BB_BURGER(
	SEQ NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	BREAD NUMBER(10) NOT NULL,
	INGREDIENT01 NUMBER(10) NOT NULL,
	INGREDIENT02 NUMBER(10) NOT NULL,
	INGREDIENT03 NUMBER(10) NOT NULL,
	INGREDIENT04 NUMBER(10) NOT NULL,
	INGREDIENT05 NUMBER(10) NOT NULL,
	INGREDIENT06 NUMBER(10) NOT NULL,
	INGREDIENT07 NUMBER(10) NOT NULL,
	INGREDIENT08 NUMBER(10) NOT NULL,
	INGREDIENT09 NUMBER(10) NOT NULL,
	CREATOR NUMBER(10) NOT NULL,
	PRICE NUMBER(20) NOT NULL,
	CAL NUMBER(20) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_BURGER_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER_SEQ FOREIGN KEY(INGREDIENT01)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE02_BURGER_SEQ FOREIGN KEY(INGREDIENT02)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE03_BURGER_SEQ FOREIGN KEY(INGREDIENT03)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE04_BURGER_SEQ FOREIGN KEY(INGREDIENT04)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE05_BURGER_SEQ FOREIGN KEY(INGREDIENT05)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE06_BURGER_SEQ FOREIGN KEY(INGREDIENT06)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER07_SEQ FOREIGN KEY(INGREDIENT07)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER08_SEQ FOREIGN KEY(INGREDIENT08)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER09_SEQ FOREIGN KEY(INGREDIENT09)
REFERENCES BB_INGREDIENT(SEQ);

INSERT INTO BB_BURGER
VALUES (BB_BURGER_SEQ.NEXTVAL, '치킨버거세트', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 5500, 5000, 0);

