--BB_FAVORITE

SELECT * FROM BB_FAVORITE;

DROP TABLE BB_FAVORITE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_FAVORITE_SEQ;

CREATE TABLE BB_FAVORITE(
	SEQ NUMBER(10) PRIMARY KEY,
	MEMBER_SEQ NUMBER(10) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_FAVORITE_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE BB_FAVORITE
ADD CONSTRAINT FK_BB_M_FAVORITE_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);