--BB_FAVORITEMENU

SELECT * FROM BB_FAVORITEMENU;

DROP TABLE BB_FAVORITEMENU
CASCADE CONSTRAINT;

DROP SEQUENCE BB_FAVORITEMENU_SEQ;

CREATE TABLE BB_FAVORITEMENU(
	SEQ NUMBER(10) PRIMARY KEY,
	FAVORITE_SEQ NUMBER(10) NOT NULL,
	MENU_SEQ NUMBER(10) NOT NULL,
	QUANTITY NUMBER(4) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_FAVORITEMENU_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE BB_FAVORITEMENU
ADD CONSTRAINT FK_BB_F_FAVORITEMENU_SEQ FOREIGN KEY(FAVORITE_SEQ)
REFERENCES BB_FAVORITE(SEQ);

