--BB_IMAGE

SELECT * FROM BB_IMAGE;

DROP TABLE BB_IMAGE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_IMAGE_SEQ;

CREATE TABLE BB_IMAGE(
	SEQ NUMBER(10) PRIMARY KEY,
	TABLE_NAME VARCHAR2(100) NOT NULL,
	WHAT_IMAGE VARCHAR2(100) NOT NULL,
	IMAGE_SRC VARCHAR2(100) NOT NULL,
	REF_SEQ NUMBER(10) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_IMAGE_SEQ
START WITH 1
INCREMENT BY 1;