--BB_LIKE

SELECT * FROM BB_LIKE;

DROP TABLE BB_LIKE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_LIKE_SEQ;

CREATE TABLE BB_LIKE(
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	BBS_SEQ NUMBER(10) NOT NULL
);

CREATE SEQUENCE BB_LIKE_SEQ
START WITH 1
INCREMENT BY 1;
