--BB_MEMBER 테이블

SELECT * FROM BB_MEMBER;

DROP TABLE BB_MEMBER
CASCADE CONSTRAINT;

DROP SEQUENCE BB_MEMBER_SEQ;

CREATE TABLE BB_MEMBER(
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(20) NOT NULL,
	BDAY VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	SEX NUMBER(1) NOT NULL,
	MILEAGE NUMBER(10) NOT NULL,
	GRADE NUMBER(10) NOT NULL,
	EXP NUMBER(10) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;
