--BB_ORDER 테이블

SELECT * FROM BB_ORDER;

DROP TABLE BB_ORDER
CASCADE CONSTRAINT;

DROP SEQUENCE BB_ORDER_SEQ;

CREATE TABLE BB_ORDER(
	SEQ NUMBER(10) PRIMARY KEY,
	MEMBER_SEQ NUMBER(10) NOT NULL,
	MEMBER_ADDR NUMBER(10) NOT NULL,
	STORE_SEQ NUMBER(10) NOT NULL,
	PRICE NUMBER(10) NOT NULL,
	ORDER_DATE DATE NOT NULL,
	STATUS NUMBER(1) NOT NULL,
	DEL NUMBER(1) NOT NULL
);
	
CREATE SEQUENCE BB_ORDER_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_MS_ORDER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_AS_ORDER_SEQ FOREIGN KEY(MEMBER_ADDR)
REFERENCES BB_ADDR(SEQ);

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_SS_ORDER_SEQ FOREIGN KEY(STORE_SEQ)
REFERENCES BB_STORE(SEQ);

