--BB_SIDE

SELECT * FROM BB_SIDE;

DROP TABLE BB_SIDE
CASCADE CONSTRAINT;

DROP SEQUENCE BB_SIDE_SEQ;

CREATE TABLE BB_SIDE(
	SEQ NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PRICE NUMBER(20) NOT NULL,
	CAL NUMBER(20) NOT NULL,
	DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE BB_SIDE_SEQ
START WITH 1
INCREMENT BY 1;